module UART_RX_TOP (
input wire RX_IN,
input wire [5:0] prescalar,
input wire PAR_EN,
input wire PAR_TYP,
input wire CLK,
input wire RST,
output wire [7:0] P_DATA,
output wire PARITY_ERROR,
output wire STOP_ERROR,
output wire DATA_VALID
);

wire DAT_SAMP_EN;
wire [4:0] EDGE_CNT;
wire [3:0] BIT_CNT;
wire ENABLE;
wire SAMPLED_BIT;
wire DESER_EN;
wire STRT_GLITCH;
wire PAR_CHK_EN;
wire STRT_CHK_EN;
wire STP_CHK_EN;


FSM_RX U_FSM (
.prescalar(prescalar),
.RX_IN(RX_IN),
.PAR_EN(PAR_EN),
.BIT_CNT(BIT_CNT),
.EDGE_CNT(EDGE_CNT),
.PAR_ERR(PARITY_ERROR),
.STP_ERR(STOP_ERROR),
.STRT_GLITCH(STRT_GLITCH),
.CLK(CLK),
.RST(RST),
.DAT_SAMP_EN(DAT_SAMP_EN),
.EDGE_BIT_CNT_EN(ENABLE),
.DESER_EN(DESER_EN),
.DATA_VALID(DATA_VALID),
.PAR_CHK_EN(PAR_CHK_EN),
.STRT_CHK_EN(STRT_CHK_EN),
.STP_CHK_EN(STP_CHK_EN)
);

EDGE_BIT_COUNTER U_EDGE_BIT_COUNTER (
.prescalar(prescalar),
.ENABLE(ENABLE),
.CLK(CLK),
.RST(RST),
.BIT_CNT(BIT_CNT),
.EDGE_CNT(EDGE_CNT)
);

DATA_SAMPLING U_DATA_SAMPLING (
.prescalar(prescalar),
.RX_IN(RX_IN),
.DAT_SAMP_EN(DAT_SAMP_EN),
.EDGE_CNT(EDGE_CNT),
.CLK(CLK),
.RST(RST),
.SAMPLED_BIT(SAMPLED_BIT)
);

DESERIALIZER U_DESERIALIZER (
.SAMPLED_BIT(SAMPLED_BIT),
.DESER_EN(DESER_EN),
.DATA_VALID(DATA_VALID),
.CLK(CLK),
.RST(RST),
.P_DATA(P_DATA)
);

STRT_CHECK U_STRT_CHECK(
.STRT_CHK_EN(STRT_CHK_EN),
.SAMPLED_BIT(SAMPLED_BIT),
.CLK(CLK),
.RST(RST),
.STRT_GLITCH(STRT_GLITCH)
);

PARITY_CHECK U_PARITY_CHECK(
.PAR_TYP(PAR_TYP),
.PAR_CHK_EN(PAR_CHK_EN),
.SAMPLED_BIT(SAMPLED_BIT),
.CLK(CLK),
.RST(RST),
.PAR_ERR(PARITY_ERROR)
);

STOP_CHECK U_STOP_CHECK(
.STP_CHK_EN(STP_CHK_EN),
.SAMPLED_BIT(SAMPLED_BIT),
.CLK(CLK),
.RST(RST),
.STP_ERR(STOP_ERROR)
);

endmodule
